feat: read zaps
v0l/snort pull request #78
Opened 2023-01-17 23:29 UTC by verbiricha

2023-01-18 10:14 UTC, v0l approved these changes
Awesome!

2023-01-18 10:14 UTC, v0l commented on src/Hash.tsx
> +export const sha256 = (str: string) => {
You can put this in Util?

2023-01-18 10:21 UTC, verbiricha commented
Follow-up PR implements zap sending (WIP) and has some improvements on this https://github.com/v0l/snort/pull/80

2023-02-04 12:47 UTC, v0l requested changes
We should also validate that the `ZapReceipt` pubkey matches the pubkey listed in the recipients lightning service, otherwise i can just fake zaps to people

2023-02-04 12:47 UTC, v0l commented on src/Element/Zap.tsx
> +    //const metaHash = sha256(zapRequest);
This is wrong, were not using this format anymore, can you revert to previous?

The `description` tag contains the zap note and the hash of this should match the description hash of the invoice

2023-02-04 13:53 UTC, v0l approved these changes

2023-02-04 13:53 UTC, merged